// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Onecore_API.Data;
using System;

namespace Onecore_API.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20190416141210_newdatabase")]
    partial class newdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Onecore_API.Models.Company", b =>
                {
                    b.Property<int>("CPY_ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("CPY_ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Onecore_API.Models.Emissores", b =>
                {
                    b.Property<int>("EM_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc_Emissor");

                    b.HasKey("EM_ID");

                    b.ToTable("Emissores");
                });

            modelBuilder.Entity("Onecore_API.Models.Employee", b =>
                {
                    b.Property<int>("EMP_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CPY_ID");

                    b.Property<int>("EMP_ADDRESSID");

                    b.Property<string>("EMP_CPF");

                    b.Property<DateTime>("EMP_DATEADMISSION");

                    b.Property<DateTime>("EMP_DATEBORN");

                    b.Property<string>("EMP_EMAIL");

                    b.Property<string>("EMP_FULLNAME");

                    b.Property<string>("EMP_GENRE");

                    b.Property<string>("EMP_PHONE");

                    b.Property<byte>("EMP_PICTURE");

                    b.Property<int>("EMP_REGISTER");

                    b.Property<string>("EMP_RG");

                    b.Property<string>("EMP_ROLE");

                    b.Property<string>("EMP_SCHOOLING");

                    b.Property<string>("EMP_TELEPHONE");

                    b.Property<int>("EM_ID");

                    b.HasKey("EMP_ID");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
